# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 09:44
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('source_type', models.IntegerField(default=1)),
                ('content', ckeditor.fields.RichTextField()),
                ('author_name', models.CharField(default='佚名', max_length=16)),
                ('create_time', models.DateTimeField()),
                ('author_url', models.URLField()),
                ('author_email', models.EmailField(max_length=254)),
                ('page_views', models.IntegerField(default=0)),
            ],
        ),
    ]
