# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='cover_img',
            field=models.URLField(default=None),
        ),
    ]
