# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 09:27
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_articlesmodel_cover_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='pre_content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
